language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - python setup.py -q install
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
script:
  - coverage run --source=loadimpact setup.py test
after_success:
  - coveralls
